muzhack-production:
  image: quay.io/aknuds1/muzhack:release
  environment:
    - ROOT_URL=https://muzhack.com
    - MONGO_URL
    - METEOR_SETTINGS
    - PRERENDER_TOKEN
    - ENVIRONMENT=production
  tags:
    - production
  autorestart: always
  deployment_strategy: every_node
nginx-production:
  image: aknudsen/meteor-frontend-server
  command: /start.sh
  tags:
    - production
  autorestart: always
  ports:
    - "443:443"
    - "80:80"
  volumes:
    - /etc/nginx/ssl/bundle.crt:/bundle.crt
    - /etc/nginx/ssl/private.key:/private.key
  links:
    - muzhack-production:backend
  deployment_strategy: every_node
logspout-production:
  image: gliderlabs/logspout
  command: syslog://logs3.papertrailapp.com:19740
  tags:
    - production
  autorestart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  deployment_strategy: every_node
