muzhack-green:
  image: quay.io/aknuds1/muzhack:omniscient
  tags:
    - muzhack-staging
  restart: always
  deployment_strategy: high_availability
muzhack-blue:
  image: quay.io/aknuds1/muzhack:omniscient
  tags:
    - muzhack-staging
  restart: always
  deployment_strategy: high_availability
lb:
  image: tutum/haproxy
  tags:
    - muzhack-staging
  restart: always
  ports:
    - "443:443"
    - "80:80"
  links:
    - muzhack-green
  roles:
    - global
logspout:
  image: gliderlabs/logspout
  command: syslog://logs3.papertrailapp.com:19740
  tags:
    - muzhack-staging
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  deployment_strategy: every_node
