muzhack-green:
  image: quay.io/aknuds1/muzhack:omniscient
  tags:
    - muzhack-green
  environment:
    - FORCE_SSL=yes
    - HAPI_IRON_PASSWORD
    - AWS_ACCESS_KEY
    - AWS_SECRET_ACCESS_KEY
    - S3_BUCKET=staging.muzhack.com
    - S3_REGION=eu-central-1
    - RETHINKDB_HOST=rethinkdb
    - RETHINKDB_AUTH_KEY
  links:
    - rethinkdb-tunnel:rethinkdb
  restart: always
  deployment_strategy: high_availability
muzhack-blue:
  image: quay.io/aknuds1/muzhack:omniscient
  tags:
    - muzhack-blue
  environment:
    - FORCE_SSL=yes
    - HAPI_IRON_PASSWORD
    - AWS_ACCESS_KEY
    - AWS_SECRET_ACCESS_KEY
    - S3_BUCKET=staging.muzhack.com
    - S3_REGION=eu-central-1
    - RETHINKDB_HOST=rethinkdb
    - RETHINKDB_AUTH_KEY
  links:
    - rethinkdb-tunnel:rethinkdb
  restart: always
  deployment_strategy: high_availability
lb:
  image: tutum/haproxy
  tags:
    - muzhack-lb
  environment:
    - EXTRA_BIND_SETTINGS=redirect scheme https code 301 if !{ ssl_fc }
    - DEFAULT_SSL_CERT
    - HEALTH_CHECK=check inter 10s fall 1 rise 2
    - MODE=http
    - OPTION=redispatch, httplog, dontlognull, forwardfor
    - TCP_PORTS=80,443
    - TIMEOUT=connect 10s, client 1020s, server 1020s
    - VIRTUAL_HOST=https://*
  restart: always
  ports:
    - "443:443"
    - "80:80"
  links:
    - muzhack-green
  roles:
    - global
  deployment_strategy: high_availability
logspout-muzhack-staging:
  image: gliderlabs/logspout
  command: syslog://logs3.papertrailapp.com:19740
  tags:
    - muzhack-staging
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  deployment_strategy: every_node
rethinkdb-tunnel:
  image: aknudsen/ssh
  tags:
    - muzhack-rethinkdb-tunnel
  target_num_containers: 2
  environment:
    - RETHINKDB_SSH_HOST
  command: -v -T -N -L *:28015:localhost:28015 root@188.166.16.45
  ports:
    - "28015:28015"
  volumes:
    - /root/.ssh:/root/.ssh:ro
  restart: always
  deployment_strategy: high_availability
