mongo:
  image: mongo:3
  command: --auth
  volumes:
    - /var/data/mongodb:/data/db
  ports:
    - "27017:27017"
  tags:
    - staging
  restart: always
muzhack-green:
  image: quay.io/aknuds1/muzhack:latest
  links:
    - mongo:db
  environment:
    - ROOT_URL=https://staging.muzhack.com
    - MONGO_URL
    - METEOR_SETTINGS
  tags:
    - staging
  restart: always
  deployment_strategy: high_availability
muzhack-blue:
  image: quay.io/aknuds1/muzhack:latest
  links:
    - mongo:db
  environment:
    - ROOT_URL=https://staging.muzhack.com
    - MONGO_URL
    - METEOR_SETTINGS
  tags:
    - staging
  restart: always
  deployment_strategy: high_availability
lb:
  image: tutum/haproxy
  tags:
    - staging
  restart: always
  ports:
    - "443:443"
    - "80:80"
  volumes:
    - /etc/nginx/ssl/bundle.crt:/bundle.crt
    - /etc/nginx/ssl/private.key:/private.key
  links:
    - muzhack-green
  roles:
    - global
logspout:
  image: gliderlabs/logspout
  command: syslog://logs3.papertrailapp.com:19740
  tags:
    - staging
  restart: always
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  deployment_strategy: every_node
