apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    db: rethinkdb
  name: rethinkdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        db: rethinkdb
        role: replicas
    spec:
      containers:
      - image: aknudsen/docker-kubernetes-rethinkdb:2.3
        name: rethinkdb
        imagePullPolicy: Always
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 8080
          name: admin-port
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        volumeMounts:
        - mountPath: /data
          name: rethinkdb-storage
      volumes:
      - name: rethinkdb-storage
        gcePersistentDisk:
          pdName: staging-disk
          fsType: ext4
