apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backup-rethinkdb
  labels:
    app: backup-rethinkdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backup-rethinkdb
    spec:
      containers:
      - name: backup-rethinkdb
        image: quay.io/aknuds1/backup-rethinkdb
        imagePullPolicy: Always
        args:
          - --host=rethinkdb-proxy
          - --file=/data/rethinkdb-dump.tar.gz
          - --project_id=muzhack-1288
          - --bucket=backup.muzhack.com
        env:
        - name: BACKUP_PRIVATE_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backup
              key: private-key-id
        - name: BACKUP_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              name: backup
              key: private-key
        - name: BACKUP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: backup
              key: client-id
        - name: BACKUP_CLIENT_EMAIL
          valueFrom:
            secretKeyRef:
              name: backup
              key: client-email
        volumeMounts:
        - mountPath: /data
          name: rethinkdb-storage
      volumes:
      - name: rethinkdb-storage
        gcePersistentDisk:
          pdName: rethinkdb-backup-disk
          fsType: ext4
